In [1]:
import os, glob
import numpy as np
from tqdm import tqdm

In [2]:
path = 'D:/wenqu/pixel_all/'
file_name = []
for a in glob.glob(os.path.join(path, '*.npy')):
    file_name.append(a)

In [3]:
file_name[1]

'D:/wenqu/pixel_all\\101999999.npy'

In [4]:
len(file_name)

136

In [5]:
np_list = []
for i in range(136):
    np_name = 'np_' + str(i)
    np_list.append(np_name)
np_list

['np_0',
 'np_1',
 'np_2',
 'np_3',
 'np_4',
 'np_5',
 'np_6',
 'np_7',
 'np_8',
 'np_9',
 'np_10',
 'np_11',
 'np_12',
 'np_13',
 'np_14',
 'np_15',
 'np_16',
 'np_17',
 'np_18',
 'np_19',
 'np_20',
 'np_21',
 'np_22',
 'np_23',
 'np_24',
 'np_25',
 'np_26',
 'np_27',
 'np_28',
 'np_29',
 'np_30',
 'np_31',
 'np_32',
 'np_33',
 'np_34',
 'np_35',
 'np_36',
 'np_37',
 'np_38',
 'np_39',
 'np_40',
 'np_41',
 'np_42',
 'np_43',
 'np_44',
 'np_45',
 'np_46',
 'np_47',
 'np_48',
 'np_49',
 'np_50',
 'np_51',
 'np_52',
 'np_53',
 'np_54',
 'np_55',
 'np_56',
 'np_57',
 'np_58',
 'np_59',
 'np_60',
 'np_61',
 'np_62',
 'np_63',
 'np_64',
 'np_65',
 'np_66',
 'np_67',
 'np_68',
 'np_69',
 'np_70',
 'np_71',
 'np_72',
 'np_73',
 'np_74',
 'np_75',
 'np_76',
 'np_77',
 'np_78',
 'np_79',
 'np_80',
 'np_81',
 'np_82',
 'np_83',
 'np_84',
 'np_85',
 'np_86',
 'np_87',
 'np_88',
 'np_89',
 'np_90',
 'np_91',
 'np_92',
 'np_93',
 'np_94',
 'np_95',
 'np_96',
 'np_97',
 'np_98',
 'np_99',
 'np_100',

In [7]:
# for i in tqdm(range(high_res_img_flatten.shape[1])):
concate_list = []
for i in tqdm(range(136)):
    np_list[i] = np.load(file_name[i])
    concate_list.append(np_list[i])

 68%|██████████████████████████████████████████████████████▊                          | 92/136 [25:34<12:13, 16.68s/it]


MemoryError: Unable to allocate 3.17 GiB for an array with shape (425000000,) and data type float64

In [ ]:
concate_file = np.concatenate(concate_list)

In [ ]:
concate_file.shape

In [4]:
x1 = np.load(file_name[0])

In [8]:
x1, x1.shape

(array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]),
 (1000000, 425))

In [5]:
x2 = np.load(file_name[1])

In [9]:
x2, x2.shape

(array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]),
 (1000000, 425))

In [12]:
x3 = np.load(file_name[2])
x3, x3.shape

(array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]),
 (1000000, 425))

In [13]:
x = np.concatenate([x1, x2, x3])

In [14]:
x, x.shape

(array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]),
 (3000000, 425))